### ISSUE TITLE
Replace ZF1 dependency with Zend_DB

### ISSUE THREAD

**Issue by aurmil** [run-as-root/magento2-prometheus-exporter#38]
hello

your package requires magento/zendframework1

https://github.com/run-as-root/magento2-prometheus-exporter/blob/3.1.4/composer.json#L46

and it seems that you only use Zend_DB classes

https://github.com/search?q=repo%3Arun-as-root%2Fmagento2-prometheus-exporter%20zend&type=code

from Magento 2.4.6,  this package is not required anymore:

2.4.5: https://github.com/magento/magento2/blob/2.4.5/composer.json#L69

2.4.6: https://github.com/magento/magento2/blob/2.4.6/composer.json#L76

related commit: https://github.com/magento/magento2/commit/7f1641bb769c4acc52ddfbdc3984011712f66166

you should remove your requirement on zf1 and add zend-db instead

**Comment by DavidLambauer** [comment]
HI @aurmil,

thank you for this report. I'll look into this ASAP

**Comment by DavidLambauer** [comment]
HI @aurmil,

@den-slepnev98 worked on it and released a new version. 

https://github.com/run-as-root/magento2-prometheus-exporter/releases/tag/3.1.5

Greetings

**Comment by aurmil** [comment]
wow that was fast! thanks :)
