### ISSUE TITLE
Add Authorization to metrics HTTP endpoint

### ISSUE THREAD

**Issue by mwr** [run-as-root/magento2-prometheus-exporter#7]

**Comment by Serializator** [comment]
What about refactoring the "/metrics" route (currently in the "frontend" area) into a REST endpoint ("webapi_rest" area) and use the native Magento integrations for token based authentication?

**Comment by DavidLambauer** [comment]
I decided to add an Authorization Header. In the System Config, you can generate a token which then needs to be configured in Prometheus. Will push soon
